### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by hossamxt** [kokspflanze/PServerCMS#6]
Hello Sir .. When i Use " Git " to use That Command 
"php composer.phar self-update" , "php composer.phar update"
i don't take any result except this "bash: php: command not found
" 
So Any Help Please ?

**Comment by kokspflanze** [comment]
like i say in chat https://github.com/kokspflanze/pserverCMSFull/blob/master/doc/windows-setup/APACHE.md#php-path-in-environment-variables
