### ISSUE TITLE
vote for coin

### ISSUE THREAD

**Issue by seaaso** [kokspflanze/PServerCMS#8]
hello dear 
i know how to do vote for silk 
but i want to know to do the vote for coins 
and where put coin id or code
hope to explain it to me
waiting you replay 
regards

![11](https://user-images.githubusercontent.com/33437628/34135040-d98fac6a-e466-11e7-8cc6-fd3b8c85a2a4.png)

**Comment by kokspflanze** [comment]
hi there is no default feature to add items, the system just add the same coins like for donation, but you can overwrite the logic with your own module and change it or write a pr for that feature

**Comment by seaaso** [comment]
idk how to do it 
how much you want 
and change it to vote for coins not silk

**Comment by kokspflanze** [comment]
you can wirte me a private message in Gitter, it depends on your skills and your sql server

**Comment by seaaso** [comment]
you can send me the link of gitter cus im not know it

**Comment by kokspflanze** [comment]
https://github.com/kokspflanze/PServerCMS/blob/master/README.md there is a button
