### ISSUE TITLE
CMS Files missing

### ISSUE THREAD

**Issue by benossa** [kokspflanze/PServerCMS#9]
Hi,
I have cloned this repository but there are no php files inside, I also searched in documentation there is no download links for web php files just guide how to setup.
Maybe I'm missing something here but can you help me explain how to download source files ?

Thank you.

**Comment by kokspflanze** [comment]
i will post all stuf in the next week, atm im busy

**Comment by benossa** [comment]
> 
> 
> i will post all stuf in the next week, atm im busy

Ok, Thanks
